name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["gh-page"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'gh-page'  # Ensure we're checking out the correct branch

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version

      - name: Build with Jekyll
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build
        with:
          source: ./
          destination: ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: ghp-deploy  # Deploy to a branch named ghp-deploy
